# DO NOT EDIT THIS LINE.
# The value will is changed automatically by our GitHub Actions workflows when preparing a new patch.
GAMEVERSION = '13.5.6'

# List of scripts to be loaded by ScriptLoader.rb. Adjust as needed.
SCRIPTS = [
  'Rejuv/Settings',
  'Rejuv/SystemConstants',

  'RPG_Sprite',
  'SpriteResizer',
  'Game_Temp',
  'Game_Data',
  'Game_Screen',
  'Game_System',
  'Game_Picture',
  'Game_CommonEvent',
  'Game_Character',
  'Game_Event',
  'Game_Player',
  'Walk_Run',
  'Game_Map',
  'Map_Scroll',

  'Spriteset_Map',
  'AnimationSprite',
  'ReflectedSprite',

  'TileDrawingHelper',

  'Interpreter',
  'Audio',
  'PBEvent',
  'PBIntl',
  'PBDebug',

  'BitmapCache',
  'Window',
  'SpriteWindow',
  'SW Subclasses',
  'LargePlane',
  'DrawText',
  'Messages',
  'TextEntry',
  'EventScene',

  'Scene_Intro',
  'Scene_Map',
  'Scene_Credits',

  'PBConstants',
  'PBStuff',
  'PBMove',
  'PBTypesExtra',
  'PBExperience',
  'PBAnimation',
  'PBScene',

  'Battle_ActiveSide',
  'Battle_DamageState',
  'Battler',
  'Battle_Effects',
  'Battle_Move',
  'Battle_MoveEffects',
  'Battle',
  'Battle_AI',
  'PBAnimation',
  'Battle_Trainer',
  'Battle_SafariZone',
  'Battle_Record',
  'Battle_Scene',
  'Battle_Peer',
  'Battle_Clauses',
  'Battle_Field',

  'Field',
  'FieldWeather',
  'Map',
  'Encounters',
  'EncounterModifiers',
  'HiddenMoves',
  'BerryPlants',
  'DayCare',
  'DependentEvents',
  'Time',
  'TimeWeather',
  'Trainers',
  'Roaming',

  'Items',
  'ItemEffects',
  'Balls',
  'PokeRadar',
  'Bag',

  'Pokemon',
  'ShadowPokemon',
  'Evolution',
  'Sprite',
  'Storage',

  'PauseMenu',
  'ReadyMenu',
  'PokedexScene',
  'Pokedex',
  'NestAndForm',
  'EggHatching',
  'Party',
  'Summary',
  'Pokegear',
  'RegionMap',
  'Jukebox',
  'PulseDex',
  'FieldNotes',
  'ItemTracker',
  'TrainerCard',
  'Trading',
  'MoveRelearner',
  'MovesetRestorer',
  'Mart',
  'HallOfFame',

  'MinigameSlotMachine',
  'MinigameVoltorbFlip',
  'MinigameLottery',
  'MinigameMining',
  'MinigameTilePuzzles',
  'Roulette Game',

  'OrgBattle',
  'OrgBattleRules',
  'OrgBattleGenerator',
  'BattleSwap',
  'Selection',

  'Options',
  'Save',
  'Load',
  'System',
  'Utilities',
  'Debug',
  'Editor',
  'TilesetEditor',
  'AnimEditor',
  'DataObjects',
  'DataObjects - Compilers',
  'DataObjects - Yeeters',
  'Compiler',

  'Battle_Online',
  'Trade',
  'Profiler',
  'Event YEET professional SP2',

  'Safari',
  'PurifyChamber',
  'Battle_SafariZone',
  'Battle_Peer',
  'Battle_Record',
  'Battle_Clauses',

  'FlyAnimation',

  'Rejuv/mapconnections',
  'Rejuv/Achievements',
  'Rejuv/AchievementsUpdate',
  'Rejuv/AchievementsScene',
  'Rejuv/AdvancedWeather',
  'Rejuv/001_VASP',
  'Rejuv/RSECableCar',
  'Rejuv/Roulette Game',
  'Rejuv/Advanced Pokedex',
  'Rejuv/CharacterSwitch',
  'Rejuv/Difficulty Modes',
  'Rejuv/GameCorner',
  'Rejuv/PokemonSelection',
  'Rejuv/RecordsTab',
  'Rejuv/Pseudo3D',
  'Rejuv/Self Switch Off',
  'Rejuv/Quest_Config',
  'Rejuv/Quest_Main',
  'Rejuv/Quest_UI',
  'Rejuv/Quest_Data',
  'Rejuv/fieldtxt',
  'Rejuv/Rejuv_MoveEffects',
  'Rejuv/Battle_Rejuv',
  'Rejuv/Battler_Rejuv',
  'Rejuv/Battle_Inspect',
  'Rejuv/PBScene_Rejuv',
  'Rejuv/BattleScene_Rejuv',
  'Rejuv/PokemonBossBattle',
  'Rejuv/BossInfo',
  'Rejuv/RaidDens',
  'Rejuv/NewGamePlus',
  'Rejuv/RegionMap',
  'Rejuv/RiftDex',
  'Rejuv/RejuvPasswords',
  'Rejuv/RejuvPokegear',
  'Rejuv/RejuvCustomScripts',
  'Rejuv/RejuvIntro',
  'Rejuv/cybernavMoveTutor',

  'cass shit',
  'haru stuff',
  'FL_SimpleHUD',

  'Cache',
  'ClientData',
  'DataConversion',
  'Main',
]
