NATUREHASH = {
:HARDY => {
		:name => "Hardy",
		:like => "spicy",
		:dislike => "spicy",
	},
:LONELY => {
		:name => "Lonely",
		:incStat => PBStats::ATTACK,
		:decStat => PBStats::DEFENSE,
		:like => "spicy",
		:dislike => "sour",
	},
:BRAVE => {
		:name => "Brave",
		:incStat => PBStats::ATTACK,
		:decStat => PBStats::SPEED,
		:like => "spicy",
		:dislike => "sweet",
	},
:ADAMANT => {
		:name => "Adamant",
		:incStat => PBStats::ATTACK,
		:decStat => PBStats::SPATK,
		:like => "spicy",
		:dislike => "dry",
	},
:NAUGHTY => {
		:name => "Naughty",
		:incStat => PBStats::ATTACK,
		:decStat => PBStats::SPDEF,
		:like => "spicy",
		:dislike => "bitter",
	},
:BOLD => {
		:name => "Bold",
		:incStat => PBStats::DEFENSE,
		:decStat => PBStats::ATTACK,
		:like => "sour",
		:dislike => "spicy",
	},
:DOCILE => {
		:name => "Docile",
		:like => "sour",
		:dislike => "sour",
	},
:RELAXED => {
		:name => "Relaxed",
		:incStat => PBStats::DEFENSE,
		:decStat => PBStats::SPEED,
		:like => "sour",
		:dislike => "sweet",
	},
:IMPISH => {
		:name => "Impish",
		:incStat => PBStats::DEFENSE,
		:decStat => PBStats::SPATK,
		:like => "sour",
		:dislike => "dry",
	},
:LAX => {
		:name => "Lax",
		:incStat => PBStats::DEFENSE,
		:decStat => PBStats::SPDEF,
		:like => "sour",
		:dislike => "bitter",
	},
:TIMID => {
		:name => "Timid",
		:incStat => PBStats::SPEED,
		:decStat => PBStats::ATTACK,
		:like => "sweet",
		:dislike => "spicy",
	},
:HASTY => {
		:name => "Hasty",
		:incStat => PBStats::SPEED,
		:decStat => PBStats::DEFENSE,
		:like => "sweet",
		:dislike => "sour",
	},
:SERIOUS => {
		:name => "Serious",
		:like => "sweet",
		:dislike => "sweet",
	},
:JOLLY => {
		:name => "Jolly",
		:incStat => PBStats::SPEED,
		:decStat => PBStats::SPATK,
		:like => "sweet",
		:dislike => "dry",
	},
:NAIVE => {
		:name => "Naive",
		:incStat => PBStats::SPEED,
		:decStat => PBStats::SPDEF,
		:like => "sweet",
		:dislike => "bitter",
	},
:MODEST => {
		:name => "Modest",
		:incStat => PBStats::SPATK,
		:decStat => PBStats::ATTACK,
		:like => "dry",
		:dislike => "spicy",
	},
:MILD => {
		:name => "Mild",
		:incStat => PBStats::SPATK,
		:decStat => PBStats::DEFENSE,
		:like => "dry",
		:dislike => "sour",
	},
:QUIET => {
		:name => "Quiet",
		:incStat => PBStats::SPATK,
		:decStat => PBStats::SPEED,
		:like => "dry",
		:dislike => "sweet",
	},
:BASHFUL => {
		:name => "Bashful",
		:like => "dry",
		:dislike => "dry",
	},
:RASH => {
		:name => "Rash",
		:incStat => PBStats::SPATK,
		:decStat => PBStats::SPDEF,
		:like => "dry",
		:dislike => "bitter",
	},
:CALM => {
		:name => "Calm",
		:incStat => PBStats::SPDEF,
		:decStat => PBStats::ATTACK,
		:like => "bitter",
		:dislike => "spicy",
	},
:GENTLE => {
		:name => "Gentle",
		:incStat => PBStats::SPDEF,
		:decStat => PBStats::DEFENSE,
		:like => "bitter",
		:dislike => "sour",
	},
:SASSY => {
		:name => "Sassy",
		:incStat => PBStats::SPDEF,
		:decStat => PBStats::SPEED,
		:like => "bitter",
		:dislike => "sweet",
	},
:CAREFUL => {
		:name => "Careful",
		:incStat => PBStats::SPDEF,
		:decStat => PBStats::SPATK,
		:like => "bitter",
		:dislike => "dry",
	},
:QUIRKY => {
		:name => "Quirky",
		:like => "bitter",
		:dislike => "bitter",
	},
}